trigger:
  - master
  - feat/*

variables:
  azureSubscriptionEndpoint: julie-ng-connection
  azureContainerRegistry: julie.azurecr.io
  registryName: $(azureContainerRegistry)/$(Build.Repository.Name)
  imageTag: $(registryName):$(Build.BuildId)

pool:
  vmImage: 'Ubuntu-16.04'

steps:

# -------------
# Node.js Steps
# -------------

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: npm install

- script: npm run lint
  displayName: Lint Code

# -------------
# Docker Steps
# -------------

- script: |
    echo '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
    echo 'buildSha set to $(buildSha)'
  displayName: Get build git sha

- script: docker build --tag $(imageTag)-$(buildSha) .
  displayName: 'Docker: Build and tag image'

# Use the task to avoid embedding credentials in pipeline
- task: Docker@1
  displayName: 'Docker: login ACR'
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- script: docker push $(imageTag)-$(buildSha)
  displayName: 'Docker: Push image'

- script: docker logout $(azureContainerRegistry)
  displayName: 'Docker: logout ACR'